databases:
  - name: nicks-blog
    databaseName: nicks-blog
    user: nicks-blog

services:
  - type: web
    name: nicks-blog
    env: ruby
    buildCommand: "./bin/setup"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nicks-blog
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true
