databases:
  - name: nicks-blog
    databaseName: blog
    user: nick

services:
  - type: redis
    name: nicks-redis
    ipAllowList: []
  - type: web
    name: nicks-blog
    env: ruby
    buildCommand: "./bin/setup"
    startCommand: "./bin/bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nicks-blog
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: nicks-redis
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true
